version: '3.8'
services:
  postgres:
    image: postgres:11
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    #    volumes:
    #      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "database", "-U", "root" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: boxfuse/flyway
    container_name: my-flyway
    volumes:
      - ./src/main/resources/flyway:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres:5432/database -user=root -password=root migrate